### ISSUE TITLE
Discuss about @api tag

### ISSUE THREAD

**Issue by rgazelot** [Taluu/Behapi#24]
As discussed, we have to use the tag @api to use --api-debug and the @debug tag.

```
Baptiste Clavié [6:18 PM] 
je voulais avoir genre soit `@rest` soit `@api`

[6:18]  
mais je pense que je vais opter pour `@rest`

[6:18]  
(parce que `DebugRest`)

[6:18]  
ou alors `DebugApi`

[6:19]  
voir `DebugHttp` en fait, ca devrait avoir plus de sens

Remy Gazelot [6:19 PM] 
+1

Baptiste Clavié [6:20 PM] 
du coup faudrait que j'introduise un tag `@http` (edited)
```

**Comment by Taluu** [comment]
Basically, I thought I would do a `@http` tag rather than `@api` + `@rest` (opening then to other engines and not limiting to REST). And renaming the `DebugRest` to `DebugHttp` or something like that, as it is in fact debugging a http request.

should be done in 0.2, I just have to tag the current state as 0.1

**Comment by Taluu** [comment]
Even better : move the `DebugRest` into a listener rather than a context, as there is no "step" per se in it
