### ISSUE TITLE
Generate code coverage from behapi test ?

### ISSUE THREAD

**Issue by mhlsf** [Taluu/Behapi#66]
Would be a really nice feature if we could generate code coverage using phpunit code coverage tool : 

https://github.com/sebastianbergmann/php-code-coverage

But from my understanding, since we are hitting the API from an external process, we cannot get proper code coverage through xdebug ? Is there a  way around that ?

**Comment by Taluu** [comment]
I think there is a behat extension for that, but I don't think it's made for external calls, because as you said it, it's an external process...

Maybe there should be some way to add in test environment a somewhat tracker of calls made, but I'm not too sure about this (and tests will take a lot longer).

**Comment by Taluu** [comment]
(Won't fix as it's not within behapi's scope)
